#!/bin/bash
VERSION=0.3.1
ARCH=i386

PWD=`pwd`
if [ "$PWD" != "/opt/ggseq-${VERSION}-${ARCH}" ]
then
  echo "Error: please copy this folder (ggseq-${VERSION}-${ARCH}) to /opt"
  exit 1
fi
if test -e "/usr/bin/ggseq" || test -e "/usr/share/icons/ggseq_32.xpm" || test -e "/usr/share/applications/ggseq.desktop"
then
  echo "Error: ggseq is already installed"
  exit 1
fi
USER=`whoami`
if [ "$USER" != "root" ]
then
  echo "Error: must be user 'root' for installation"
  exit 1
fi
echo "Linking ggseq to /usr/bin/ggseq"
ln -s /opt/ggseq-${VERSION}-${ARCH}/ggseq /usr/bin/ggseq
echo "Linking ggseq_32.xpm to /usr/share/icons/ggseq_32.xpm"
ln -s /opt/ggseq-${VERSION}-${ARCH}/ggseq_32.xpm /usr/share/icons/ggseq_32.xpm
echo "Linking ggseq.desktop to /usr/share/applications/ggseq.desktop"
ln -s /opt/ggseq-${VERSION}-${ARCH}/ggseq.desktop /usr/share/applications/ggseq.desktop
echo
echo "= Installation finished ="
echo

