//------------------------------------------------------------------------------
// Header generated by wxDesigner from file: ggseq_ui.wdr
// Do not modify this file, all changes will be lost!
//------------------------------------------------------------------------------

#ifndef __WDR_ggseq_ui_H__
#define __WDR_ggseq_ui_H__

#if defined(__GNUG__) && !defined(__APPLE__)
    #pragma interface "ggseq_ui_wdr.h"
#endif

// Include wxWindows' headers

#ifndef WX_PRECOMP
    #include <wx/wx.h>
#endif

#include <wx/image.h>
#include <wx/statline.h>
#include <wx/spinbutt.h>
#include <wx/spinctrl.h>
#include <wx/splitter.h>
#include <wx/listctrl.h>
#include <wx/treectrl.h>
#include <wx/notebook.h>
#include <wx/grid.h>

// Declare window functions

#define ID_MAIN_SPLITTER 10000
wxSizer *MainFrameFunc( wxWindow *parent, bool call_fit = TRUE, bool set_sizer = TRUE );

#define ID_DIRTREE 10001
wxSizer *DirTreePanelFunc( wxWindow *parent, bool call_fit = TRUE, bool set_sizer = TRUE );

#define ID_TL_PANEL 10002
#define ID_SLIDER 10003
#define ID_LISTCTRL 10004
#define ID_TEXT 10005
#define ID_BITMAPBUTTON 10006
wxSizer *TimelinePanelFunc( wxWindow *parent, bool call_fit = TRUE, bool set_sizer = TRUE );

#define ID_VOLUME_SLIDER 10007
extern wxSizer *m_sidebarSizer;
#define ID_TL_FILELIST 10008
#define ID_TL_SIDEPANEL 10009
#define ID_TL_MINIPLAYER 10010
wxSizer *TimelinePanelFunc2( wxWindow *parent, bool call_fit = TRUE, bool set_sizer = TRUE );

#define ID_FRAMES_CTRL 10011
#define ID_SECONDS_CTRL 10012
#define ID_BPM_CTRL 10013
#define ID_PRESET_LISTBOX 10014
#define ID_PRESET_NAME_TEXTCTRL 10015
#define ID_DELETE_BUTTON 10016
#define ID_NEW_BUTTON 10017
wxSizer *SetSnapFunc( wxWindow *parent, bool call_fit = TRUE, bool set_sizer = TRUE );

#define ID_COLOUR_DIRTREE 10018
#define ID_COLOUR_LISTBOX 10019
#define ID_COLOUR_ADD_BUTTON 10020
#define ID_COLOUR_REMOVE_BUTTON 10021
#define ID_COLOUR_BUTTON 10022
wxSizer *SetColourFunc( wxWindow *parent, bool call_fit = TRUE, bool set_sizer = TRUE );

#define ID_NOTEBOOK 10023
wxSizer *PreferencesFunc( wxWindow *parent, bool call_fit = TRUE, bool set_sizer = TRUE );

#define ID_ACCELS_GRID 10024
wxSizer *SetAccelsFunc( wxWindow *parent, bool call_fit = TRUE, bool set_sizer = TRUE );

// Declare menubar functions

#define ID_MENU 10025
#define ID_NEW 10026
#define ID_OPEN 10027
#define ID_SAVE 10028
#define ID_SAVEAS 10029
#define ID_WAV_EXPORT 10030
#define ID_QUIT 10031
#define ID_UNDO 10032
#define ID_REDO 10033
#define ID_ADD_TRACK 10034
#define ID_DELETE_TRACK 10035
#define ID_MOVE_TRACK_UP 10036
#define ID_MOVE_TRACK_DOWN 10037
#define ID_PREFERENCES 10038
#define ID_SHOW_MIXER 10039
#define ID_ABOUT 10040
wxMenuBar *MyMenuBarFunc();

// Declare toolbar functions

#define ID_REWIND 10041
#define ID_PLAY 10042
#define ID_STOP 10043
#define ID_TOOL 10044
void MyToolBarFunc( wxToolBar *parent );

// Declare bitmap functions

wxBitmap GgseqBitmapsFunc( size_t index );

#endif

// End of generated file
