import os

env = Environment(CC = 'g++',
	CCFLAGS='-D_WIN32_IE=0x400 -D__WXMSW__ -mthreads  -fno-pcc-struct-return -O2 -MMD -mthreads -Wall -ID:\\wxWindows-2.4.2\\lib\\wx\\include\\mswu-2.4 -ID:\\wxWindows-2.4.2\\include',
	LINKFLAGS = '-Wl,--subsystem,windows -mwindows -mthreads',
	ENV = {'PATH' : os.environ['PATH']}, tools=['mingw'])

src_list = Split("""BigScrollBar.cpp
	colour_helper.cpp
	dial.cpp
	DisableListener.cpp
	EnvelopeDragHandler.cpp
	FileInfoPanel.cpp
	ggEvtHandler.cpp
	ggseq_ui.cpp
	ggseq_ui_wdr.cpp
	GgseqDocManager.cpp
	GgseqGlobalProps.cpp
	ImportPackDialog.cpp
	MiniFilerTest.cpp
	MiniPlayer.cpp
	MouseDragHandler.cpp
	PlayerInterface.cpp
	PreferencesDialog.cpp
	RubberDragHandler.cpp
	Ruler.cpp
	SampleEdit.cpp
	SelectionDragHandler.cpp
	ShortcutsDialog.cpp
	SidePanel.cpp
	SoundManager.cpp
	StatusProgressBar.cpp
	tinystr.cpp
	tinyxml.cpp
	tinyxmlerror.cpp
	tinyxmlparser.cpp
	TLColourManager.cpp
	TLData.cpp
	TLItem.cpp
	TLLoadSaveManager.cpp
	TLMiniFiler2.cpp
	TLMuteButton.cpp
	TLPanel.cpp
	TLSample.cpp
	TLSampleManager.cpp
	TLSelectColourDialog.cpp
	TLSelectionSet.cpp
	TLSetSnapDialog.cpp
	TLTrack.cpp
	TLTrackVolumeDial.cpp
	TLView.cpp
	TLXmlLoader2.cpp
	TrimmerDialog.cpp
	ui_helper.cpp
	UpdateListener.cpp
	WaveEditor.cpp""")

lib_list = Split("""wxmsw242u
	rpcrt4
	oleaut32
	ole32
	uuid
	winspool
	winmm
	shell32
	comctl32
	ctl3d32
	advapi32
	wsock32""")

env.Program('ggseq', src_list,
	lib_list,
	LIBPATH=['D:\\wxWindows-2.4.2\\lib'] )















